before_install:
  - npm config set strict-ssl false

install:
  - sudo apt-get install nodejs
  - sudo apt-get install npm
  - sudo npm install -g markdown-link-check

before_script:
  - npm config set strict-ssl true

script:
  - ./check_dead_links.sh
